# Puedes agregar esto a tu workflow para más detalles
- name: Generate HTML coverage report
  run: coverage html

- name: Upload coverage report as artifact
  uses: actions/upload-artifact@v3
  with:
    name: coverage-report
    path: htmlcov/
        
    - name: SonarCloud Scan
      uses: SonarSource/sonarqube-scan-action@v1
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
